apiVersion: v1
kind: Service
metadata:
  name: db #connection will fail if you didnt use db as name
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    image: postgres #use or copy selector as defined in pod
